### ISSUE TITLE
Improve request Body hashing

### ISSUE THREAD

**Issue by pquerna** [mailgun/lemma#6]
in `auth.go`, `ioutil.ReadAll` is called on the request Body.  While suitable for small messages, this is not an ideal interface for larger request bodies.

I'd like to suggest that two things be thought about:

1) Extending the signing format, to allow the request body to be added to the MAC pre-hashed, eg, instead of doing `mac.Write(body)`, have it be `mac.Write(sha512(body))` or other ways to allow the body to be hashed separately.

2) Allow the `req.Body` to interface upgrade to a `HashValue()` or similiar interface, so worst case the implementer could make it do a streaming hash of the request body, but it potentially could also use a previously calculated hash.

**Comment by russjones** [comment]
@pquerna I'll look into how we can make signing the body more efficient.
